version: 2.1

jobs:
  test:
    docker:
      - image: cimg/rust:1.58.1
    steps:
      - checkout
      - run: cargo --version
      - run:
          name: Check
          command: "cargo check"
      - run:
          name: Test
          command: "cargo test"


workflows:
  code-quality-workflow:
    jobs:
      - test